package:
  name: expat
  version: 2.4.9
  epoch: 1
  description: "XML SAX Parser library written in C"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:

secfixes:
  2.4.9-r0:
    - CVE-2022-40674

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
      - /work/packages
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - tree

pipeline:
  - uses: fetch
    with:
      uri: https://downloads.sourceforge.net/project/expat/expat/${{package.version}}/expat-${{package.version}}.tar.bz2
      expected-sha256: 7f44d1469b110773a94b0d5abeeeffaef79f8bd6406b07e52394bcf48126437a

  - uses: autoconf/configure
    with:
      opts: --datadir=/usr/share
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
  - runs: tree

subpackages:
  - name: expat-dev
    description: expat headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - expat
  - name: expat-docs
    description: expat docs
    pipeline:
      - uses: split/manpages
