package:
  name: jdk17
  version: 17.0.4.1
  epoch: 0
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: |
        Apache License, Version 2.0
        Eclipse Distribution License 1.0 (BSD)
        Eclipse Public License 2.0
        一 (Secondary) GNU General Public License, version 2 with OpenJDK Assembly Exception
        一 (Secondary) GNU General Public License, version 2 with the GNU Classpath Exception
  dependencies:
    runtime:
      - zlib

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
      - /work/packages
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - file
      - freetype-dev
      - cups-dev
      - libx11-dev
      - libxext-dev
      - libxrender-dev
      - libxrandr-dev
      - libxtst-dev
      - libxt-dev
      - alsa-lib-dev
      - libffi-dev
      - bash
      - zip

pipeline:
  # should we just use OpenJDK directly rather than adoptium?
  - uses: fetch
    with:
      uri: https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
      expected-sha256: 323d6d7474a359a28eff7ddd0df8e65bd61554a8ed12ef42fd9365349e573c2c
      strip-components: 0
  - uses: fetch
    with:
      uri: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4.1%2B1/OpenJDK17U-jdk-sources_17.0.4.1_1.tar.gz
      expected-sha256: 0583e39652126c739078ad8836eedb08c0e323cc3871392d6df632ed11e7d93c
  - runs: chmod +x configure
  - uses: autoconf/configure
    with:
      opts: |
        --with-boot-jdk=./jdk-16.0.2+7 \
        --with-vendor-name=Wolfi \
        --with-vendor-url=https://en.wikipedia.org/wiki/Octopus_wolfi \
        --with-vendor-bug-url=https://github.com/wolfi-dev/os/issues \
        --with-version-opt="wolfi-r${{package.epoch}}"
  - runs: make jdk-image

  # - uses: autoconf/make
  # - uses: autoconf/make-install

subpackages:
  - name: jdk17_dev
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.subpkgdir}}/usr/lib/libintl.so.* ${{targets.subpkgdir}}/usr/lib
          chmod +x ${{targets.subpkgdir}}/usr/lib/libintl.so.*

          mkdir -p ${{targets.subpkgdir}}/usr/lib/jvm/java-17-openjdk
          cp -r ${{targets.destdir}}/build/linux-*-server-release/images/jdk/* ${{targets.subpkgdir}}/usr/lib/jvm/java-17-openjdk/
    description: Java Development Kit 17
